Instruction context:
   
 L. 134       302  CALL_FUNCTION_1       1  ''
                 304  RAISE_VARARGS_1       1  'exception instance'
               306_0  COME_FROM           292  '292'
               306_1  COME_FROM           156  '156'
->               306  JUMP_FORWARD        346  'to 346'
               308_0  COME_FROM            46  '46'

test/267.pyc -- 
# decompile failed

# file test/267.pyc
# Deparsing stopped due to parse error
